[formatting]
align_comments       = true
align_entries        = true
array_auto_collapse  = true
array_trailing_comma = false
crlf                 = false
indent_string        = '	'
reorder_arrays       = true
reorder_keys         = true
trailing_newline     = true
